language: python
python: 2.7
install: "pip install -r requirements.txt"
script:
 - coverage run manage.py test -v 2
 - coverage xml
 - coverage report
after_success:
 - codecov
 - python-codacy-coverage -r coverage.xml